import { PAGES_PREFIX_PATH } from "constants/route.constant";
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
} from "constants/navigation.constant";
import { ADMIN, USER } from "constants/roles.constant";

const pagesNavigationConfig = [
  {
    key: "pages",
    path: "",
    title: "PAGES",
    translateKey: "nav.pages.pages",
    icon: "pages",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: "pages.welcome",
        path: `${PAGES_PREFIX_PATH}/welcome`,
        title: "Welcome",
        translateKey: "nav.pages.welcome",
        icon: "welcome",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.pm",
        path: "/new",
        title: "Product Management",
        translateKey: "nav.pages.accessDenied",
        icon: "productManagement",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.pl",
        path: "/access-denied",
        title: "Location",
        translateKey: "nav.pages.accessDenied",
        icon: "Location",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Customer Order Management",
        translateKey: "nav.pages.accessDenied",
        icon: "customerOrderManagement",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Supplier Management",
        translateKey: "nav.pages.accessDenied",
        icon: "supplierManagement",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Supplier Controle Center",
        translateKey: "nav.pages.accessDenied",
        icon: "supplierControleCenter",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Dispatch Notification",
        translateKey: "nav.pages.accessDenied",
        icon: "dispatchNotification",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Dellivery Callan",
        translateKey: "nav.pages.accessDenied",
        icon: "delliveryCallan",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Payment",
        translateKey: "nav.pages.accessDenied",
        icon: "Payment",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Customer Onboarding",
        translateKey: "nav.pages.accessDenied",
        icon: "customerOnboarding",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Sales Order",
        translateKey: "nav.pages.accessDenied",
        icon: "salesOrder",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "pages.accessDenied",
        path: "/access-denied",
        title: "Supplier PO",
        translateKey: "nav.pages.accessDenied",
        icon: "accessDenied",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
    ],
  },
];

export default pagesNavigationConfig;
