import React from "react";
import {
  HiOutlineChartSquareBar,
  HiOutlineUserGroup,
  HiOutlineTrendingUp,
  HiOutlineUserCircle,
  HiOutlineBookOpen,
  HiOutlineCurrencyDollar,
  HiOutlineShieldCheck,
  HiOutlineColorSwatch,
  HiOutlineChatAlt,
  HiOutlineDesktopComputer,
  HiOutlinePaperAirplane,
  HiOutlineChartPie,
  HiOutlineUserAdd,
  HiOutlineKey,
  HiOutlineBan,
  HiOutlineHand,
  HiOutlineDocumentText,
  HiOutlineTemplate,
  HiOutlineLockClosed,
  HiOutlineDocumentDuplicate,
  HiOutlineViewGridAdd,
  HiOutlineShare,
  HiOutlineVariable,
  HiOutlineCode,
  HiNewspaper,
  HiLocationMarker,
  HiIdentification,
  HiTruck,
  HiHand,
  HiMailOpen,
  HiClipboardList,
  HiCurrencyRupee,
  HiUserGroup,
  
} from "react-icons/hi";

const navigationIcon = {
  apps: <HiOutlineViewGridAdd />,
  project: <HiOutlineChartSquareBar />,
  crm: <HiOutlineUserGroup />,
  sales: <HiOutlineTrendingUp />,
  crypto: <HiOutlineCurrencyDollar />,
  knowledgeBase: <HiOutlineBookOpen />,
  account: <HiOutlineUserCircle />,
  uiComponents: <HiOutlineTemplate />,
  common: <HiOutlineColorSwatch />,
  feedback: <HiOutlineChatAlt />,
  dataDisplay: <HiOutlineDesktopComputer />,
  forms: <HiOutlineDocumentText />,
  navigation: <HiOutlinePaperAirplane />,
  graph: <HiOutlineChartPie />,
  authentication: <HiOutlineLockClosed />,
  signIn: <HiOutlineShieldCheck />,
  signUp: <HiOutlineUserAdd />,
  forgotPassword: <HiOutlineLockClosed />,
  resetPassword: <HiOutlineKey />,
  pages: <HiOutlineDocumentDuplicate />,
  welcome: <HiOutlineHand />,
  // accessDenied: <HiOutlineBan />,
  productManagement: <HiNewspaper />,
  Location: <HiLocationMarker />,
  customerOrderManagement: <HiIdentification />,
  supplierManagement: <HiTruck />,
  supplierControleCenter: <HiHand />,
  dispatchNotification: <HiMailOpen />,
  delliveryCallan: <HiClipboardList />,
  Payment: <HiCurrencyRupee />,
  customerOnboarding: <HiUserGroup />,
  salesOrder: <HiClipboardList />,
  asdfv:<HiIdentification/>,
  guide: <HiOutlineBookOpen />,
  documentation: <HiOutlineDocumentText />,
  sharedComponentDoc: <HiOutlineShare />,
  utilsDoc: <HiOutlineVariable />,
  changeLog: <HiOutlineCode />,
};

export default navigationIcon;
